### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/zig#1]
Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is sorely outdated but
quite possibly better than nothing (I'm so sorry, I'm waaaay behind on getting
documentation updated).
https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

Check out https://github.com/orgs/exercism/teams/track-maintainers/discussions/1
for details about the #maintainers channel in the exercism-team Slack workspace.

Please ask if you have any questions or if anything is confusing!

**Comment by massivelivefun** [comment]
A list of tasks (which should be done before going underway with exercise creation):

1. Add myself to the list of maintainers.
2. Update the docs/ files to be filled with content related to Zig.
3. Update the track's CI from Travis to Github Actions. #2

**Comment by massivelivefun** [comment]
> 
> 
> A list of tasks (which should be done before going underway with exercise creation):
> 
>     1. Add myself to the list of maintainers.
> 
>     2. Update the docs/ files to be filled with content related to Zig.
> 
>     3. Update the track's CI from Travis to Github Actions. #2

All of the tasks quoted above are done following these pull requests: #3, #6, #7, #27
