### ISSUE TITLE
bump Zig from `0.10.1` to `0.11.0-dev.2777+b95cdf0ae` (at least)

### ISSUE THREAD

**Issue by ee7** [exercism/zig#244]
The Exercism Zig track should try to stay in sync with the main [online learning resources for Zig](https://ziglang.org/learn/#online-learning-resources): ziglearn and ziglings.

Both are supposed to track the Zig `master` release. But ziglearn hasn't been updated for the new for loop syntax yet, which was a breaking change. Ziglings was updated, and [even has a new exercise for it][1].

Let's wait until ziglearn is updated, and then do the below:

- [x] bump Zig in the test runner repo
- [x] check that it deploys correctly
- [x] if it does deploy correctly, bump Zig in this repo soon afterwards
- [x] add a track-wide update message, stating the new minimum supported version

[1]: https://github.com/ratfactor/ziglings/commit/47c871041c8f55ec3f9d8f810402038d38d4ecbc#diff-ab5f88f1966a8a033b646eab525d6455f1bb326dc726f6466a36bf4f6ba735cd

**Comment by booniepepper** [comment]
0.11.0 was planned for _today_ according to [news on the site](https://ziglang.org/news/0.11.0-postponed-again/)

The milestone only has a couple issues left in it: https://github.com/ziglang/zig/milestone/17

Feel free to assign me as a reviewer to anything related to this
