### ISSUE TITLE
exercises(collatz-conjecture): clarify error

### ISSUE THREAD

**Issue by ee7** [exercism/zig#364]
See:

- https://github.com/exercism/zig/pull/360#issuecomment-1815159705
- https://github.com/exercism/zig/pull/363#issuecomment-1873940161

I'll fix this soon.

**Comment by SamOr1014** [comment]
Hi, just wanna say this would be a great update for the exercise. I myself just trying to learn zig from scratch but this exercise is unclear on the declaring error part. I have to spend more time to find out that i have to add my own error handling (from the tests) than to finish the exercise. Adding clearer instructions might really help on solidifying users skills on the language than spending time to find out a hidden requirement.
