### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by iHiD** [exercism/zig#427]
@keiravillekode You have qualified to be a maintainer here. Thank you for your hard work! Would you like to join?

**Comment by iHiD** [comment]
(cc @keiravillekode - I got your username wrong before sorry!)

**Comment by keiravillekode** [comment]
Yes, I would be happy to join the Zig maintainers.

**Comment by ErikSchierboom** [comment]
@keiravillekode Awesome. Thank you!

You're part of the team now. You also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)
