### ISSUE TITLE
KOTP Maintainer Permissions

### ISSUE THREAD

**Issue by massivelivefun** [exercism/zig#57]
Hello @ErikSchierboom, although @kotp has been given approval to become a maintainer for the Zig track #50, he does not have the typical maintainer permissions on this repo, for instance please refer to PR #52's comments. What are the methods to navigate towards giving him maintainer permissions, such as pr merging, and the like?

**Comment by ErikSchierboom** [comment]
Aha, I know what to do: call in backup! @iHiD Could you give @kotp the right permissions?

**Comment by iHiD** [comment]
Done.
