### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by kristoff-it** [exercism/zig#9]
Hi all, I'm here to lend a hand with Zig content!

Strong opening I know, but it's because I'm conscious of the fact that we are moving very fast with the language, and that we don't have extensive documentation yet, outside of the language reference.

I hope at the very least to help you answer questions about nuanced details, confusing and/or not-well-documented features, and about Zig's roadmap, so you can give a bit of extra shelf life to the exercises.

If you'll have me, I'll also be happy to help you more directly with the content.

For great justice,
Loris

**Comment by iHiD** [comment]
Awesome. Hello 🙂 . If you've not already emailed erik@exercism.io, please do, and he can get you setup on Slack etc.

You join at an exciting point in Exercism's evolution as we're soon to release our version 3 - a huge release rebuild of the site. Although you won't be able to get fully ready between now and launch, getting Zig in at it's most basic state for that would be great, and is totally achievable! :)

Putting together 20 exercises (which you can largely fork from our central repository) and a Test Runner, will mean that we can put the track live, and that people can solve it in our in-browser editor once v3 launches :)

(cc @erikschierboom)

**Comment by ErikSchierboom** [comment]
Great! I've sent you an email @kristoff-it!

**Comment by hiljusti** [comment]
@kristoff-it I'm a fan of Zig Showtime! (And also your "Why Go in a world where Rust exists?" article)

I haven't gotten around to contributing to this repo yet, but more than happy to review.

**Comment by ErikSchierboom** [comment]
I'm going through the open issues to see which ones can be closed. I think this one can? If not, feel free to re-open.
